embedding_size: 64
feat_embed_dim: 64

n_mm_layers: 1
n_layers: 2
knn_k: 10
mm_image_weight: 0.1
learning_rate: [0.0001]
reg_weight: [0.001]

start_expert_num: 4
start_gate_selection: softmax
initializer_weight: [0.1, 0.5, 0.5]

#dropout: [0.3 0.5]
#dropout: [0.1, 0.3, 0.5, 0.7]
dropout: [0.5]

#mask_weight_f: [1, 2]
#mask_weight_f: [1, 1.5, 2, 2.5, 3]
mask_weight_f: [1.5]

#temp: [0.2, 0.4, 0.8]
temp: [0.6]
#temp: [0.1]


hyper_parameters: ["reg_weight", "learning_rate", 'dropout', 'mask_weight_f', 'temp']